config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"


  root to: 'about#promo'
  mount Spree::Core::Engine, at: '/store'
  get '/about', to: 'about#mission'
  get '/me', to: 'about#me'
  get '/support', to: 'about#support'
  get '/news', to: 'posts#index'
  get '/news/:id', to: 'posts#show'
  get '/videos', to: 'videos#index'
  post '/subscribe', to: 'email#subscribe'
  post '/unsubscribe', to: 'email#unsubscribe'
  post '/promo', to: 'about#promo'

  get ENV['SECRET_URL'] + '/:id' + '/edit', to: 'posts#edit'
  post ENV['SECRET_URL'] + '/:id' + '/update', to: 'posts#update'
  post ENV['SECRET_URL'] + '/:id' + '/delete', to: 'posts#delete', as: :delete_post
  post ENV['SECRET_URL'] + '/create', to: 'posts#create', as: :create_post
  get ENV['SECRET_URL'] + '/new', to: 'posts#new', as: :new_post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
  validates_uniqueness_of :address
end

app/models/post.rb
class Post < ApplicationRecord
  self.per_page = 5

  def display_time
    created_at.strftime('%B %d %Y')
  end

  def display_image
    return thumbnail if Rails.application.assets_manifest.files.values.map{|v| v['logical_path']}.include?("#{thumbnail}")
    'missing.jpg'
  end
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def me
  end

  def mission
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  def subscribe
    begin
      email = Email.create!(address: params["email"])
      @message = "#{email.address}, you have successfully subscribed!"
    rescue => e
      @message = "Something went wrong: #{e.message}"
    end
  end

  def unsubscribe
    begin
      email = Email.where(email: params["email"]).update!(unsubscribed: true)
      @message = "You have successfully unsubscribed #{email.address} from all email communication."
    rescue => e
      @message = "We're sorry, something went wrong: #{e.message}"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end

  def new
    @posts = Post.all
    @post = Post.new()
  end

  def index
    @posts = Post.paginate(:page => params[:page]).order(created_at: :desc).to_a
    @featured = @posts.shift if [nil, "1"].include?(params[:page])
  end

  def edit
    @posts = Post.all
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(
      title: post_params[:title],
      summary: post_params[:summary],
      content: post_params[:content],
      thumbnail: post_params[:thumbnail],
      audio: post_params[:audio]
    )
    redirect_to '/' + ENV['SECRET_URL'] + '/' + @post.id.to_s + '/edit'
  end

  def create
    @post = Post.new()
    @post.update(
      title: post_params[:title],
      summary: post_params[:summary],
      content: post_params[:content],
      thumbnail: post_params[:thumbnail],
      audio: post_params[:audio]
    )
    @post.save
    redirect_to root_url
  end

  def delete
    @post = Post.find(params[:id])
    @post.delete
    redirect_to ENV['SECRET_URL'] + '/' + Post.last.id.to_s + '/edit'
  end

  private

  def post_params
    params.permit(:title, :summary, :content, :utf8, :authenticity_token, :commit, :thumbnail, :audio)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.order(post_date: :desc).to_a
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/me.html.erb
<section class='welcome message'>
  <article class='title'>
    <h1>Hi, I'm Mr. Beeken!</h1>
  </article>
  <article class='headshot'>
    <%= image_tag 'facepic.jpg', alt: 'This is a headshot of me. I know my hair looks kind of messy. I dont shampoo very often because I am kind of a hippy and think it might damage my hair.', title: 'Hi! This is my face.' %>
  </article>
  <article class='text'>
    <p>
      I'm a content creator. I love making jam packed educational videos that are exciting and fun.
      Laughter and enthusiasm are absolutely essential for learning.
    </p>
    <p>
      Originally from Salem, OR, I have always loved music and singing (evidenced by two over the shoulder piano shots.)
    </p>
    <section class='photos'>
      <article class='photo'>
        <%= image_tag 'baby.jpg', alt: 'A picture of me as a baby sitting at a piano. I look confused.', title: 'my best years as a performer' %>
      </article>
      <article class='photo'>
        <%= image_tag 'teen.jpg', alt: 'A picture of angsty tween me playing my grandfathers pump organ. Its really old but really fun to play.', title: 'angsty teen years' %>
      </article>
    </section>
    <p>
      I went to theater camp for the choir class but ended up contracting a love of theater and improv comedy too.
      It's so amazing what is possible with <u>just your body and your mind</u>!
      I studied music education at Northern Arizona University and landed a job teaching high school choir after graduating.
      Although I absolutely loved teaching, I found I could be so much more effective merging technology and education.
      So, I quit after just one year and took a day job as a web developer... and Mr. Beeken was born shortly after.
      Here I am today, trying as hard as I can to use the internet for good!
      Free education is so important to our world and the world deserves a great learning experience.
    </p>
    <p>
      To those who have supported Mr.Beeken: from the bottom of my heart, thank you so much!
      You share my vision of free, high quality educational content for all and together we are making it happen!
    </p>
    <p>
      Again, thank you so much! Stay excited and always be learning. The most important ingredients in life!
    </p>
    <p>
      With gratitude,
    </p>
  </article>
  <article class='signature'>
    <%= image_tag 'signature.png', alt: 'This is my signature. I put it here because I want to emphasize how sincere I am!', title: 'Thank you!' %>
  </article>
</section>

app/views/about/mission.html.erb
<section class='welcome message'>
  <header class='mission-statement'>
    <h2>making music literacy <em>fun</em>!</h2>
  </header>
  <article class='text'>
    <p>
      This project's philosophy is in line with Music Matters by Dave Elliot and believes in the Kodaly method.
    </p>
    <p>
      Music making gives us enjoyment, self growth and self knowledge. I believe that music education
      is part of a well rounded education and a fulfilling life.
    </p>
    <p>
      Musicianship is a multidimensional form of knowledge that is practice-specific and seated within several
      contexts: global, historical, cultural, social, individual, etc.
    </p>
    <p>
      Mr. Beeken hopes to deliver <strong>formal knowledge</strong> in a fun and accessible format.
      It also hopes to inspire curiosity and critical thinking from the viewer. At the same time,
      I hope to emphasize that music theory <strong>helps</strong> you interact with the world of music.
      It is not a secret code that is only available to gifted students, geniuses or prodigies.
    </p>
    <p>
      Music making helps us get into a <a href="https://en.wikipedia.org/wiki/Flow_(psychology)">flow</a>
      state. You don't need to know anything about Western Music tradition or notation to experience this.
      On the other hand, it is helpful to have a formal understanding of your musical world.
    </p>
    <p>
      Mr. Beeken hopes to ease the "fun gap" that exists between making music and learning about
      music theory using <strong>comedy, laughter and honesty</strong>.
    </p>
  </article>
  <a href='/me'>
    about me
  </a>
</section>

app/views/about/news.html.erb
<section class='feed'>
  <% @posts.each do |post| %>
    <article class='post jumbotron'>
        <section class='post-title'>
          <a href=<%= 'news/' + post.id.to_s %>
            <h2><strong><%= post.title %></strong></h2>
          </a>
        </section>
      <hr>
      <section class='post-date'>
        <p><%= @timestamp %></p>
      </section>
      <section class='post-body'>
        <%= post.summary %>
      </section>
    </article>
  <% end %>
</section>

app/views/about/promo.html.erb
<div class='promo'>
  <article class='promo-blurb'>
    <header class='promo-blurb-left'>
      <header class='promo-blurb-title'>
        Welcome!
      </header>
      <article class='promo-blurb-body'>
        Mr.Beeken is a Youtube channel that aims to teach basic music theory in a fun and practical way.
      </article>
    </header>
    <article class='promo-blurb-photo'>
      <%= video_tag('intro.mp4', autoplay: true, loop: true) %>
    </article>
  </article>

  <article class='promo-blurb'>
    <header class='promo-blurb-left'>
      <header class='promo-blurb-title'>
        It's Edutainment
      </header>
      <article class='promo-blurb-body'>
        Amongst a sea of boring music tutorials, Mr. Beeken’s videos are fun,
        fast paced and jam packed with educational content.
      </article>
    </header>
    <article class='promo-blurb-photo'>
      <%= video_tag('teaching.mp4', autoplay: true, loop: true) %>
    </article>
  </article>


  <article class='promo-blurb'>
    <header class='promo-blurb-left'>
      <header class='promo-blurb-title'>
        Used by Teachers
      </header>
      <article class='promo-blurb-body'>
        Teachers are using these videos more and more in their classroom to bring humor to a traditionally difficult subject.
      </article>
    </header>
    <article class='promo-blurb-photo'>
      <%= video_tag('solfege.mp4', autoplay: true, loop: true) %>
    </article>
  </article>

  <article class='promo-blurb'>
    <header class='promo-blurb-left'>
      <header class='promo-blurb-title'>
        Safe for Work
      </header>
      <article class='promo-blurb-body'>
        There is no swearing or (inappropriately) dark themes in Mr. Beeken. However, these lessons intended for ages 12 to infinity so expect satire, sarcasm, parody and panache.
      </article>
    </header>
    <article class='promo-blurb-photo'>
      <%= video_tag('why.mp4', autoplay: true, loop: true) %>
    </article>
  </article>

  <article class='promo-blurb'>
    <header class='promo-blurb-left'>
      <header class='promo-blurb-title'>
        So what do I do?
      </header>
      <article class='promo-blurb-body'>
        You can read articles and behind the scenes info on the <a href='/news'>news feed</a>. You can also find links to all video lessons on the <a href='/videos'>videos page</a>!
      </article>
    </header>
    <article class='promo-blurb-subscribe'>
      <section class='email-subscription-form jumbotron'>
        <section class='email-label'>
          <h3>Please join the mailing list.</h3>
          <p>We'll let you know first about some big plans around the corner!</p>
        </section>
        <%= form_tag(subscribe_path, method: 'post') do |f| %>
          <%= label_tag 'Email' %>
          <%= email_field_tag(:email, '', class: 'email-form', placeholder: 'your@email.com') %>
          <section class='submit-button'>
            <%= submit_tag 'Subscribe' %>
          </section>
        <% end %>
      </section>
    </article>
  </article>
</div>

app/views/about/support.html.erb
<section>
  <section class='support-explanation'>
    <h1 class='patreon-link-spacer'>
      <%= link_to raw("Continue to Patreon <icon class='fa fa-arrow-right'></icon>"), 'https://www.patreon.com', class: 'patreon-link' %>
    </h1>
      <h2>
        wait, what is Patreon?
      </h2>
      <p class='support-answer'>
        Patreon is a website that allows online creators like me to reward you for your donation.
        It's like kickstarter but the projects are ongoing.
      </p>
    <hr>
      <h2>
        how does it work?
      </h2>
      <p class='support-answer'>
        You sign up for an account on Patreon and then make a pledge to support Mr. Beeken.
        Mr. Beeken's Patreon will then charge you the amount of your pledge <strong> when a video is released</strong>.
        Video release times will vary from video to video.
      </p>
    <hr>
      <h2> ...but I don't want to pay several times a month!?!</h2>
        <p class='support-answer'>
          You can cap your per video pledge at a <strong>monthly maximum</strong>.
          So there are no surprises when you are charged.
        </p>
    <hr>
      <h2> cool! What are your rewards?</h2>
      <p class='support-answer'>
        Check out my reward tiers below.
        There are <strong>one time rewards</strong> for first time pledgers and <strong>recurring rewards</strong> that you
        can receive each time a new video is released.
      </p>
    <hr>
    <section class='rewards-tables'>
      <table class='table'>
        <tr>
          <th>
            <h3>
              One Time Rewards
            </h3>
          </th>
          <%= render 'layouts/reward_table_header', path: '1.png', text: "Learner's Permit" %>
          <%= render 'layouts/reward_table_header', path: '3.png', text: 'License to Laugh' %>
          <%= render 'layouts/reward_table_header', path: '10.png', text: 'Gentleperson/Scholar' %>
          <%= render 'layouts/reward_table_header', path: '25.png', text: 'Expecto Patreonum!' %>
          <%= render 'layouts/reward_table_header', path: '50.png', text: 'I want to be involved' %>
          <%= render 'layouts/reward_table_header', path: '100.png', text: 'Citizen Sponsor' %>
        </tr>
        <%= render 'layouts/reward_row', title: 'License to Learn PDF', rewards: [true, true, true, true, true, true] %>
        <%= render 'layouts/reward_row', title: '+ $10 Store Credit', rewards: [false, false, true, true, true, true] %>
        <%= render 'layouts/reward_row', title: '+ $15 Store Credit', rewards: [false, false, false, true, true, true] %>
        <%= render 'layouts/reward_row', title: 'Thank You Postcard', rewards: [false, false, false, true, true, true] %>
        <%= render 'layouts/reward_row', title: 'Oval Sticker', rewards: [false, false, false, true, true, true] %>
        <%= render 'layouts/reward_row', title: '+ 10 Oval Stickers', rewards: [false, false, false, false, true, true] %>
      </table>
      <hr>
      <table class='table'>
        <tr>
          <th>
            <h3>
              Recurring Rewards
            </h3>
          </th>
          <%= render 'layouts/reward_table_header', path: '1.png', text: "Learner's Permit" %>
          <%= render 'layouts/reward_table_header', path: '3.png', text: 'License to Laugh' %>
          <%= render 'layouts/reward_table_header', path: '10.png', text: 'Gentleperson/Scholar' %>
          <%= render 'layouts/reward_table_header', path: '25.png', text: 'Expecto Patreonum!' %>
          <%= render 'layouts/reward_table_header', path: '50.png', text: 'I want to be involved' %>
          <%= render 'layouts/reward_table_header', path: '100.png', text: 'Citizen Sponsor' %>
        </tr>
        <%= render 'layouts/reward_row', title: '10% Store Discount', rewards: [true, true, true, true, true, true] %>
        <%= render 'layouts/reward_row', title: 'Blooper Reels', rewards: [false, true, true, true, true, true] %>
        <%= render 'layouts/reward_row', title: 'Videos 1 Week Early', rewards: [false, false, true, true, true, true] %>
        <%= render 'layouts/reward_row', title: 'Store Codes and Sales', rewards: [false, false, false, true, true, true] %>
        <%= render 'layouts/reward_row', title: 'Episode Notes', rewards: [false, false, false, false, true, true] %>
        <%= render 'layouts/reward_row', title: 'Future Episode Discussion', rewards: [false, false, false, false, true, true] %>
        <%= render 'layouts/reward_row', title: 'Personal Thank You Video', rewards: [false, false, false, false, false, true] %>
        <%= render 'layouts/reward_row', title: 'Brought To You By: Your Name', rewards: [false, false, false, false, false, true] %>
      </table>
    </section>
  </section>
  <h1 class='patreon-link-spacer'>
    <%= link_to raw("Continue to Patreon <icon class='fa fa-arrow-right'></icon>"), 'https://www.patreon.com', class: 'patreon-link' %>
  </h1>
</section>

app/views/about/videos.html.erb
<article class='videos-message'>
  <p>Visit my <a href='www.youtube.com'>Youtube channel</a> to see more!
  </article>
<section class='videos'>
  <article class='video'>
    <iframe src="https://www.youtube.com/embed/Qkuqjrwlkxk" frameborder="0" allowfullscreen></iframe>
  </article>
  <article class='video'>
    <iframe src="https://www.youtube.com/embed/aBqoXGLxBWU" frameborder="0" allowfullscreen></iframe>
  </article>
  <article class='video'>
    <iframe src="https://www.youtube.com/embed/F4pT4s8hUVM" frameborder="0" allowfullscreen></iframe>
  </article>
  <article class='video'>
    <iframe src="https://www.youtube.com/embed/wEy0UvbICT8" frameborder="0" allowfullscreen></iframe>
  </article>
  <article class='video'>
    <iframe src="https://www.youtube.com/embed/WVNZBKbYOc8" frameborder="0" allowfullscreen></iframe>
  </article>
</section>

app/views/posts/edit.html.erb
<section class='edit-form'>
  <%= form_tag(root_url + ENV['SECRET_URL'] + '/' + @post.id.to_s + '/update') do |f| %>
    <%= label_tag 'Title' %>
    <%= text_field_tag(:title, @post.title, class: 'edit-title') %>
    <br>
    <%= label_tag 'Image name' %>
    <%= text_field_tag(:thumbnail, @post.thumbnail, class: 'edit-thumbnail') %>
    <br>
    <%= label_tag 'Summary' %>
    <%= text_field_tag(:summary, @post.summary, class: 'edit-summary') %>
    <br>
    <%= label_tag 'Audio File Name' %>
    <%= text_area_tag(:audio, @post.audio, class: 'edit-audio') %>
    <br>
    <%= text_area_tag(:content, @post.content, class: 'edit-content') %>
    <br>
    <%= submit_tag 'Update' %>
  <% end %>
  <%= form_tag(root_url + '/' + ENV['SECRET_URL'] + '/' + @post.id.to_s + '/delete') do |f| %>
    <%= submit_tag 'DELETE POST', data: { confirm: 'Are you sure?' } %>
  <% end %>
</section>

<section class='menu'>
  <% @posts.each do |post| %>
    <%= link_to (post.title || post.id.to_s), root_url + '/' + ENV['SECRET_URL'] + '/' + post.id.to_s + '/edit' %>
    <br>
  <% end %>
</section>

<%= link_to ('New Post'), :new_post %>

app/views/posts/index.html.erb
<section class='page-header'>
  <section class='page-title'>
    <% if @featured %>
      <h1>Featured Post</h1>
    <% end %>
  </section>
</section>
<section class='email-subscription-form jumbotron'>
  <section class='email-label'>
    <h3>Let me know about new posts!</h3>
  </section>
  <%= form_tag(subscribe_path, method: 'post') do |f| %>
    <%= label_tag 'Email' %>
    <%= email_field_tag(:email, '', class: 'email-form', placeholder: 'your@email.com') %>
    <section class='submit-button'>
      <%= submit_tag 'Subscribe' %>
    </section>
  <% end %>
</section>
<section class='feed'>
  <% if @featured %>
    <section class='featured'>
      <article class='post-preview jumbotron'>
        <section class='post-thumbnail'>
          <%= link_to image_tag(@featured.display_image, class: 'post-thumbnail-img'), 'news/' + @featured.id.to_s %>
        </section>
        <section class='post-descriptions'>
          <section class='post-title'>
            <a href=<%= 'news/' + @featured.id.to_s %>
              <strong><%= @featured.title %></strong>
            </a>
          </section>
          <hr>
          <section class='post-date'>
            <%= @featured.display_time %>
          </section>
          <section class='post-summary'>
            <%= @featured.summary %>
          </section>
        </section>
      </article>
    </section>
    <% if @posts %>
      <section class='page-title'>
        <h1>Recent Posts</h1>
      </section>
    <% end %>
  <% end %>
  <% @posts.each do |post| %>
    <section class='past-articles'>
      <article class='post-preview jumbotron'>
        <section class='post-thumbnail'>
          <%= link_to image_tag(post.display_image, class: 'post-thumbnail-img'), 'news/' + post.id.to_s %>
        </section>
        <section class='post-descriptions'>
          <section class='post-title'>
            <a href=<%= 'news/' + post.id.to_s %>
              <strong><%= post.title %></strong>
            </a>
          </section>
          <hr>
          <section class='post-date'>
            <%= post.display_time %>
          </section>
          <section class='post-summary'>
            <%= post.summary %>
          </section>
        </section>
      </article>
    </section>
  <% end %>
  <%= will_paginate @posts %>
</section>

app/views/posts/new.html.erb
<section class='edit-form'>
    <%= form_tag(root_url + ENV['SECRET_URL'] + '/create') do |f| %>
    <%= label_tag 'Title' %>
    <%= text_field_tag(:title, @post.title, class: 'edit-title') %>
    <br>
    <%= label_tag 'Image name' %>
    <%= text_field_tag(:thumbnail, @post.thumbnail, class: 'edit-thumbnail') %>
    <br>
    <%= label_tag 'Summary' %>
    <%= text_field_tag(:summary, @post.summary, class: 'edit-summary') %>
    <br>
    <%= label_tag 'Audio File Name' %>
    <%= text_area_tag(:audio, @post.audio, class: 'edit-audio') %>
    <br>
    <%= text_area_tag(:content, @post.content, class: 'edit-content') %>
    <br>
    <%= submit_tag 'Update' %>
  <% end %>
</section>

<section class='menu'>
  <% @posts.each do |post| %>
    <%= link_to (post.title || post.id.to_s), root_url + ENV['SECRET_URL'] + '/' + post.id.to_s + '/edit' %>
    <br>
  <% end %>
</section>

app/views/posts/show.html.erb
<% set_meta_tags og: {
  image: image_url(@post.display_image),
  title: @post.title,
  description: @post.summary,
  site_name: 'mrbeeken'
  } %>

<% if @post.audio %>
  <% set_meta_tags og: { audio: asset_url(@post.audio) } %>
<% end %>

<section class='post'>
  <section class='title'>
    <%= @post.title %>
  </section>
  <section class='photo'>
    <%= image_tag(@post.display_image) %>
  </section>
  <% if @post.audio %>
    <section class='audio'>
      <p>Listen to an audio recording of this article</p>
      <audio controls>
        <source src=<%= asset_path(@post.audio) %> type="audio/mpeg">
        Your browser does not support the audio element.
      </audio>
    </section>
  <% end %>
  <section class='misc-info'>
    <section class='timestamp'>
      <%= @post.display_time  %>
    </section>
    <section class='author'>
      Alex Beeken
    </section>
  </section>
  <hr>
  <section class='content'>
    <%= @post.content.html_safe %>
  </section>
  <section class='social'>
    <section class='social-button'>
      <%= facebook_button %>
    </section>
    <section class='social-button'>
      <%= linkedin_button %>
    </section>
    <section class='social-button'>
      <%= twitter_button %>
    </section>
    <section class='social-button'>
      <%= google_plus_button %>
    </section>
  </section>
  <section class='email'>
    Feel free to share your thoughts on this subject or anything else by emailing me at musiccramsessions@gmail.com.
  </section>
</section>

app/views/spree/checkout/_address.html.erb
<div class="columns alpha six" data-hook="billing_fieldset_wrapper">
  <fieldset id="billing" data-hook>
    <%= form.fields_for :bill_address do |bill_form| %>
      <legend align="center"><%= Spree.t(:billing_address) %></legend>
      <%= render partial: 'spree/address/form', locals: { form: bill_form, address_type: 'billing', address: @order.bill_address } %>
    <% end %>
  </fieldset>
</div>

<div class="columns omega six" data-hook="shipping_fieldset_wrapper">
  <fieldset id="shipping" data-hook>
    <%= form.fields_for :ship_address do |ship_form| %>
      <legend align="center"><%= Spree.t(:shipping_address) %></legend>
      <p class="field checkbox" data-hook="use_billing">
        <%= check_box_tag 'order[use_billing]', '1', @order.shipping_eq_billing_address? %>
        <%= label_tag :order_use_billing, Spree.t(:use_billing_address), id: 'use_billing' %>
      </p>
      <%= render partial: 'spree/address/form', locals: { form: ship_form, address_type: 'shipping', address: @order.ship_address } %>
    <% end %>
  </fieldset>
</div>
<hr class="clear" />

<div class="form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), class: 'continue button primary' %>
  <% if try_spree_current_user %>
    <span data-hook="save_user_address">
      &nbsp; &nbsp;
      <%= check_box_tag 'save_user_address', '1', try_spree_current_user.respond_to?(:persist_order_address) %>
      <%= label_tag :save_user_address, Spree.t(:save_my_address) %>
    </span>
  <% end %>
</div>

app/views/spree/checkout/_confirm.html.erb
<fieldset id="order_details" data-hook>
  <div class="clear"></div>
  <legend align="center"><%= Spree.t(:confirm) %></legend>
  <%= render partial: 'spree/shared/order_details', locals: { order: @order } %>
</fieldset>

<br />

<div class="form-buttons" data-hook="buttons">
  <% Spree::Frontend::Config[:require_terms_and_conditions_acceptance].tap do |requires_acceptance| %>
    <% if requires_acceptance %>
      <div class="terms_and_conditions" data-hook="terms_and_conditions">
        <div class="policy"><%= render partial: "spree/checkout/terms_and_conditions" %></div>
        <%= check_box_tag :accept_terms_and_conditions, 'accepted', false %>
        <%= label_tag :accept_terms_and_conditions, Spree.t(:agree_to_terms_of_service) %>
      </div>
    <% end %>

    <%= submit_tag Spree.t(:place_order),
      disabled: requires_acceptance,
      class: "continue button primary #{ 'disabled' if requires_acceptance }" %>
  <% end %>

  <script>Spree.disableSaveOnClick();</script>
</div>

app/views/spree/checkout/_terms_and_conditions.en.html.erb
Put your terms and conditions here

app/views/spree/checkout/edit.html.erb
<div id="checkout" data-hook>
  <%= render partial: 'spree/shared/error_messages', locals: { target: @order } %>

  <div class="row" data-hook="checkout_header">
    <h1 class="columns three alpha" data-hook="checkout_title"><%= Spree.t(:checkout) %></h1>
    <div class="columns thirteen omega" data-hook="checkout_progress"><%= checkout_progress %></div>
  </div>

  <div class="row" data-hook="checkout_content">
    <div class="columns <%= if @order.state != 'confirm' then 'alpha twelve' else 'alpha omega sixteen' end %>" data-hook="checkout_form_wrapper">
      <%= form_for @order, url: update_checkout_path(@order.state), html: { id: "checkout_form_#{@order.state}" } do |form| %>
        <% if @order.state == 'address' || !@order.email? %>
          <p class="field" style='clear: both'>
            <%= form.label :email %><br />
            <%= form.text_field :email %>
          </p>
        <% end %>
        <%= render @order.state, form: form %>
      <% end %>
    </div>
    <% if @order.state != 'confirm' %>
      <div id="checkout-summary" data-hook="checkout_summary_box" class="columns omega four">
        <%= render partial: 'summary', locals: { order: @order } %>
      </div>
    <% end %>
  </div>
</div>

<script>
Spree.current_order_id = "<%= @order.number %>"
Spree.current_order_token = "<%= @order.guest_token %>"
</script>

<% if I18n.locale != :en %>
  <%= javascript_include_tag 'jquery.validate/localization/messages_' + I18n.locale.to_s.downcase.gsub('-', '') %>
<% end %>

app/views/spree/checkout/existing_payment/_gateway.html.erb
<tr id="<%= dom_id(wallet_payment_source, 'spree')%>" class="<%= cycle('even', 'odd') %>">
  <td><%= wallet_payment_source.payment_source.name %></td>
  <td><%= wallet_payment_source.payment_source.display_number %></td>
  <td><%= wallet_payment_source.payment_source.month %></td>
  <td><%= wallet_payment_source.payment_source.year %></td>
  <td>
    <%= radio_button_tag "order[wallet_payment_source_id]", wallet_payment_source.id, default, class: "existing-cc-radio" %>
  </td>
</tr>

app/views/spree/products/_image.html.erb
<% if defined?(image) && image %>
  <%= image_tag image.attachment.url(:product), itemprop: "image" %>
<% else %>
  <%= image_tag @product.display_image.attachment(:product), itemprop: "image" %>
<% end %>